commands:
  give: on
  fly: on
  owner-kit: on
  remove-owner-kit: on
  gamemode: on
  mkstack: on
  bag: on
  uuid: on
  ret: on
  invsee: on
  offlinegm: on
  ench: on
  dead_inventory: on
  boost_librarian: on

crafts:
  debug-stick: on
  emerald: off
  enchanted-golden-apple: off
  spawner: on
  spawner-eggs: on

enchantments.max_level: 900