# Enable or disable command handlers
commands:
  give: on
  fly: on
  owner-kit: on
  remove-owner-kit: on
  gamemode: on
  mkstack: on
  bag: on
  uuid: on
  ret: on
  invsee: on
  offlinegm: on
  ench: on
  dead_inventory: on
  boost_librarian: on

# Enable or disable crafts
crafts:
  debug-stick: on
  emerald: off
  enchanted-golden-apple: off
  spawner: on
  spawner-eggs: on

# Maximum enchantment experience level cost for survival players (def: 900)
enchantments:
  max_level: 900


# Speed: How fast the cart will travel (max: 6, def: 1)
# Rideable: Apply properties to passenger carts.
# Explosive: Apply properties to explosive (tnt) carts.
# Hopper: Apply properties to hopper carts.
# Powered: Apply properties to powered (furnace) carts.
# Storage: Apply properties to storage (chest) carts.
bc:
  properties:
    speed: 1
  carts:
    rideable: true
    explosive: false
    hopper: false
    powered: false
    storage: true