# Enable or disable command handlers

commands:
  give: on
  fly: on
  owner-kit: on
  remove-owner-kit: on
  gamemode: on
  mkstack: on
  bag: on
  uuid: on
  ret: on
  invsee: on
  offlinegm: on
  ench: on
  dead_inventory: on
  boost_librarian: on

# Enable or disable crafts
crafts:
  debug-stick: on
  emerald: off
  enchanted-golden-apple: off
  spawner: on
  spawner-eggs: on

# Maximum enchantment experience level cost for survival players
enchantments:
  max_level: 900


# Momentum: How far a cart will travel (def: 32)
# Speed: How fast the cart will travel (def: 8)
# Derail: Allow carts to derail on slopes/corners (def: true)
# Rideable: Apply properties to passenger carts.
# Explosive: Apply properties to explosive (tnt) carts.
# Hopper: Apply properties to hopper carts.
# Powered: Apply properties to powered (furnace) carts.
# Storage: Apply properties to storage (chest) carts.

bc:
  properties:
    momentum: 128
    speed: 16
    derail: true
  carts:
    rideable: true
    explosive: false
    hopper: false
    powered: false
    storage: true